### ISSUE TITLE
漢字を開くかどうか

### ISSUE THREAD

**Issue by momdo** [waic/translation_guidelines#28]
waic/wcag20 Wikiより

>- 「分かりやすい」と「わかりやすい」
>- 「分かる」と「わかる」
>
>（↑16/06/22 今井さん記載分）
>
> JIS 本文では「全て」と漢字表記していて、WCAG 2.0解説書では「すべて」とひらいている場合。

**Comment by momdo** [comment]
「わかる」と「分かる」は次のリソースが信頼できるでしょうか。
<a href="http://www.mitsumura-tosho.co.jp/webmaga/kotoba/detail17.html">教科書の言葉 Q&A 第17回 	「わかる」と「分かる」の使い分けは？| みつむら web magazine | 光村図書出版</a>

これによると、開いてしまった方が良さそうですね。

一方「全て」と「すべて」ですが、JIS Z 8301によれば、
>G.2用字 
G.2.1漢字
漢字の用い方（字種・音訓・字体）は， 常用漢字表（昭和 56.10.1 内閣告示第 1 号） による。

というのが原則です。常用漢字表には「全て」が記載されています。また、[公用文における漢字使用等について](http://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/sanko/koyobun/pdf/kunrei.pdf)では、

>１ 漢字使用について
(2) 「常用漢字表」の本表に掲げる音訓によって語を書き表すに当たっては，次の事項に留意する。
（中略）
イ 次のような副詞及び連体詞は，原則として，漢字で書く。
例（副詞）
（中略）全て（以下略）

と明示されています。これらのルールに厳密に従うならば、漢字になります。

**Comment by caztcha** [comment]
もんどさん、issue 立て、ありがとうございます。
なるほど、と思いつつ、個人的には「全て」という漢字表記に引っかかりを感じています。
その理由としては、(私が元取説屋だったこともあり「テクニカルライティング」に触れていた経緯から) 副詞および副詞的に使う語は常用漢字表にある漢字でもひらくのが慣例になっている、というのがあります。
http://www.yamanouchi-yri.com/yrihp/techwrt-2-4s/t-2-4s03fa.htm

もっとも、公的な指針ではなく、通例にすぎませんが...。

**Comment by momdo** [comment]
> 「全て」という漢字表記に引っかかりを感じています。

もし私が自分で文章書くならば、そのように表記しないだろう、と思うところではありますね。

表記に関する問題はいくつか論点があるでしょうが、JISの表記ルールがテクニカルライティングを含めた一般的な慣習から結構離れているために、結果としてJISのルールから外れてしまうというのは挙げられるでしょうか。

ある程度JISルールに忠実なガイドラインが必要とされる一方で、そもそも守れないガイドラインを作ってもあまり意味がないわけでして、どうするものかなあ、というのはあります。

**Comment by caztcha** [comment]
> もし私が自分で文章書くならば、そのように表記しないだろう、と思うところではありますね。

そう、それ（↑）なんですよね...。

> JISの表記ルールがテクニカルライティングを含めた一般的な慣習から結構離れているために、結果としてJISのルールから外れてしまうというのは挙げられるでしょうか。

「テクニカルライティングを含めた一般的な慣習」がまとまっている感じではなさそうなので、少し時間がかかりますが、トライしてみましょうか。

// 手軽な参考例としては、新聞社が出している「用字用語ハンドブック」的なものもありますが、**書籍 (Web 上のリソースではない)** を**購入しないと**入手できないので、難しいですよね...

**Comment by momdo** [comment]
> // 手軽な参考例としては、新聞社が出している「用字用語ハンドブック」的なものもありますが、書籍 (Web 上のリソースではない) を購入しないと入手できないので、難しいですよね...

ウェブで見られる、信頼できるものとしては、JTFスタイルガイドぐらいですかね。
https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf#page=19

>「テクニカルライティングを含めた一般的な慣習」がまとまっている感じではなさそうなので、少し時間がかかりますが、トライしてみましょうか。

やってみる価値はあるのではないでしょうか。土屋さんがまとめてくださるなら、対比群として、厳密にJISの規則に従った場合の用字についてまとめる用意はあります:-)

**Comment by caztcha** [comment]
> JISの表記ルールがテクニカルライティングを含めた一般的な慣習から結構離れているために、結果としてJISのルールから外れてしまうというのは挙げられるでしょうか。

まとめてみました。[翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)に追記する想定で、書いてみましたが、いかがでしょうか。

--- (ここから) ---

## 用字【G.2】
- 漢字は、常用漢字表にある漢字を目安に使用します。
- 以下については、常用漢字表にある漢字表記がある場合も、読みやすさを優先するためにかな表記をします。
  - 副詞 (例 : さらに、すでに、すべて、まったく、もっとも)
  - 接続詞 (例 : および、かつ、したがって、ただし、ならびに、または、もしくは、ゆえに)
  - 副助詞 (例 : ～など、～ほど、～まで)
  - 形式名詞 (例 : ～するうえで、～すること、～するたび、～するため、～のとおり、～するとき)
  - 補助的な動詞 (例 : ～していただく、～しておく、～してください、～してみる、～による、～がわかる)
  - 助動詞 (例 : ～のごとく、～しない、～のような)

--- (ここまで) ---

参考にしたソースは以下です。

- http://www.yamanouchi-yri.com/yrihp/techwrt-2-4s/t-2-4s03fa.htm
- http://www.yamanouchi-yri.com/yrihp/techwrt-2-4s/t-2-4s03fb.htm
- https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf#page=19

ただし、これだと読みやすくはなりますが、現時点での翻訳ガイドラインと競合するので (「及び」「又は」の漢字表記など)、議論が必要ですね。

**Comment by momdo** [comment]
厳密にJISの規則に従った場合の用字をまとめました（このとおり運用しなければならないという案ではありません）。

## 用字【G.2】
漢字の使用は、[常用漢字表](http://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/naikaku/pdf/joyokanjihyo_20101130.pdf)の「本表」と「付表」（「表の見方及び使い方」を含む。）を目安にします。常用漢字表の「本表」に従う場合に、次の事項に留意します。
### 副詞および連体詞は原則として、漢字とします。
例：余り　必ず　極めて　更に　少し　既に　全て　例えば　常に　特に　再び　全く　最も　専ら　僅かに
ただし、次のような副詞は原則としてかなとします。
例：かなり　ふと　やはり　よほど
### 接続詞は、かなとします。
例：おって　かつ　したがって　ただし　また　ゆえに
ただし、次の四つについては、漢字とします。
及び　並びに　又は　若しくは
### 助動詞および助詞は、かなで書きます。
例：～ない　～ようだ　～ぐらい　～だけ　～ほど
### 次のような語句を、（）の中に示した例のように用いるときは、かなで書きます。
- ある（その点に問題がある。）
- いる（ここに関係者がいる。）
- こと（許可しないことがある。）
- できる（だれでも利用ができる。）
- とおり（次のとおりである。）
- とき（事故のときは連絡する。）
- ところ（現在のところ差し支えない。）
- とも（説明するとともに意見を聞く。）
- ない（欠点がない。）
- なる（合計すると１万円になる。）
- ほか（そのほか～，特別の場合を除くほか～）
- もの（正しいものと認める。）
- ゆえ（一部の反対のゆえにはかどらない。）
- わけ（賛成するわけにはいかない。）
- ～かもしれない（間違いかもしれない。）
- ～てあげる（図書を貸してあげる。）
- ～ていく（負担が増えていく。）
- ～ていただく（報告していただく。）
- ～ておく（通知しておく。）
- ～てください（問題点を話してください。）
- ～てくる（寒くなってくる。）
- ～てしまう（書いてしまう。）
- ～てみる（見てみる。）
- ～てよい（連絡してよい。）
- ～にすぎない（調査だけにすぎない。）
- ～について（これについて考慮する。）

**Comment by caztcha** [comment]
もんどさん、ありがとうございます。
その前の私のコメントと比べてみて :

> ### 副詞および連体詞は原則として、漢字とします。
...のところを JIS どおりにすべきか or 開くか

> ### 接続詞は、かなとします。
...の例外 (及び　並びに　又は　若しくは) をどうするか (JIS どおりにすべきか or 開くか)

以上2点が論点になる感じですね。
WG4 の皆さんにとって、運用しやすい (ルールとしてブレなく守りやすい) ほうをチョイスできればいいかなと思います。

**Comment by momdo** [comment]
しかも、現行のWCAG 2.0ルールは特殊で、接続詞については、「及び」、「又は」、「並びに」は漢字な一方で、「もしくは」はかな書きという変則ルールなのですよね…。

**Comment by caztcha** [comment]
2018-09-27 の WG4 ミーティングで、「読みやすさは重視するものの、敢えて開くべき積極的な理由がなければ、JIS Z 8301に則るのが無難」という方向性で話がまとまりました。運用 (翻訳時の WG4 メンバーによる徹底にしやすさや、JIS X8341-3 への展開時の置換作業の手間など) を考えると、現実的かなと思います。 

「若しくは」→「もしくは」など、変則ルールについては、例外としてリストアップするのが現実的かな、という話になりました。

---

もんどさんのご意見もお伺いしたいです。
そのうえで、ガイドライン化はどうしましょう？私の方でドラフトを用意する、でもOKです。 :)

**Comment by momdo** [comment]
> 読みやすさは重視するものの、敢えて開くべき積極的な理由がなければ、JIS Z 8301に則るのが無難

この基本方針で構わないと思います。ガイドラインに何も言及がない、という現状がまず問題だと思いますので。

>「若しくは」→「もしくは」など、変則ルールについては、例外としてリストアップするのが現実的かな、という話になりました。

JIS Z 8301から明示的に外れる場合は、その旨が明示されていればOKだと思います。

>そのうえで、ガイドライン化はどうしましょう？私の方でドラフトを用意する、でもOKです。 :)

では土屋さんにドラフトの用意をお願いします。

**Comment by caztcha** [comment]
ドラフトを作ってみました。[翻訳ガイドライン](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)の「用字【G.2】」を編集する想定です。

ポイントは以下の通りです。

- 「用字【G.2】」冒頭の箇条書きの順番を変更。漢字について内容が大幅に追加されるため、漢字をいちばん下に移動。
- h3 見出し「副詞および連体詞は原則として、漢字とします。」以降を追加。2018-09-27 の WG4 ミーティングでの検討 (基本はJIS Z 8301に則る) から、[上にあるもんどさんコメント](https://github.com/waic/translation_guidelines/issues/28#issuecomment-419630094)を基本としています。
- JIS Z 8301の例外 (さしあたっては、「若しくは」→「もしくは」) については、末尾に「例外事項」としてリストアップすることも検討しましたが、「適用されないルールが上に書かれていて、よくよく下まで読まないと例外であることが伝わらない」状態もよくないと思い、都度、該当箇所に追記する形を採っています。

（ちなみに、「若しくは」→「もしくは」の例外については、翻訳ガイドラインの中の「[andの訳語候補、「及び」「かつ」「並びに」【G.3.3.b】、orの訳語候補、「又は」「もしくは」【G.3.3.c】](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md#andの訳語候補及びかつ並びにg33borの訳語候補又はもしくはg33c)」にも、既に記述があるで、重複する形になりそうですが、さてどうしたものか逡巡しています。）

こんな感じでよろしければ、プルリクエストを出そうと思いますが、いかがでしょうか？

--- (ここから) ---

## 用字【G.2】

- 仮名遣いは、[現代仮名遣い](http://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/naikaku/gendaikana/index.html)を使用します。
- 送り仮名は、[送り仮名の付け方](http://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/naikaku/okurikana/index.html)と[法令における漢字使用等について](http://www.clb.go.jp/info/other/houreiniokerukanji.pdf)を目安にします。
- 漢字は、[常用漢字表](http://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/naikaku/kanji/index.html)の「本表」と「付表」（「表の見方及び使い方」を含む。）を目安にします。常用漢字表の「本表」に従う場合に、次の事項に留意します。

### 副詞および連体詞は原則として、漢字とします。

例：余り　必ず　極めて　更に　少し　既に　全て　例えば　常に　特に　再び　全く　最も　専ら　僅かに

ただし、次のような副詞は原則としてかなとします。

例：かなり　ふと　やはり　よほど

### 接続詞は、かなとします。

例：おって　かつ　したがって　ただし　また　ゆえに　もしくは

ただし、次の接続詞は、漢字とします。

例：及び　並びに　又は

<small>(「若しくは／もしくは」の表記は、JIS Z 8301 及び常用漢字表では漢字で表記しますが、読みやすさのためWAICでは「もしくは」とひらがなで表記しています。)</small>

### 助動詞および助詞は、かなで書きます。

例：～ない　～ようだ　～ぐらい　～だけ　～ほど

### 次のような語句を、（）の中に示した例のように用いるときは、かなで書きます。

- ある（その点に問題がある。）
- いる（ここに関係者がいる。）
- こと（許可しないことがある。）
- できる（だれでも利用ができる。）
- とおり（次のとおりである。）
- とき（事故のときは連絡する。）
- ところ（現在のところ差し支えない。）
- とも（説明するとともに意見を聞く。）
- ない（欠点がない。）
- なる（合計すると１万円になる。）
- ほか（そのほか～，特別の場合を除くほか～）
- もの（正しいものと認める。）
- ゆえ（一部の反対のゆえにはかどらない。）
- わけ（賛成するわけにはいかない。）
- ～かもしれない（間違いかもしれない。）
- ～てあげる（図書を貸してあげる。）
- ～ていく（負担が増えていく。）
- ～ていただく（報告していただく。）
- ～ておく（通知しておく。）
- ～てください（問題点を話してください。）
- ～てくる（寒くなってくる。）
- ～てしまう（書いてしまう。）
- ～てみる（見てみる。）
- ～てよい（連絡してよい。）
- ～にすぎない（調査だけにすぎない。）
- ～について（これについて考慮する。）

--- (ここまで) ---

**Comment by momdo** [comment]
よいのではないかと。プルリクエストを出してもらえば、ミーティングでマージするかどうかの判断ができるかと思います。

**Comment by caztcha** [comment]
本 issue 冒頭の「わかる」or「分かる」問題についても、ドラフトを追記してコミットしました。

**Comment by momdo** [comment]
マージいただいたので閉じます。
