### ISSUE TITLE
全角文字と半角文字が混在する際のルール

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/translation_guidelines#3]
文中に全角文字と半角文字が混在する場合は、半角スペースで区切るということでよいでしょうか？
> ウェブサイトは CAPTCHA の使用を

は、

> ウェブサイトはCAPTCHAの使用を

とはしないかんじですか？

**Comment by momdo** [comment]
>文中に全角文字と半角文字が混在する場合は、半角スペースで区切るということでよいでしょうか？

区切るというよりもむしろ、「見やすさのため、日本語と英数字の間には半角スペースを挿入する」という感じでしょうか。
またこれには但し書きがあって、「ただし、句読点、括弧などの日本語の約物と英数字が隣接する場合は挿入しない」というのも必要ですね（すでにうっすらと書いているつもりですが）。

いずれにせよ舌足らずなので、ガイドラインに追記する必要はありますね。

**Comment by jidaikobo-shibata** [comment]
反応ありがとうございます。

じつは
https://waic.jp
のほうは、このスペースは取り去ってしまう方向で整理が進んでいたのです。

だから、WAICでは、

> WCAG 2.0達成方法集

だけど、リンク先は、

> WCAG 2.0 達成方法集

なんです。

今回は訳出ガイドラインなので、場違いな話なんですが、なんとなく、WAICと、WAIC提供の文書とで不統一があると気になりますね……。（ごめんなさい。この部分、コメント、ご放念にただいてもけっこうです。ただSlackから言及する用に投稿だけさせてください）

**Comment by momdo** [comment]
「括弧」と「分かち書き」にスペースの話があり、スペースの話を一括りにした方がよい、のかもしれません。
