### ISSUE TITLE
用語集についてまとめる

### ISSUE THREAD

**Issue by bakera** [waic/translation_guidelines#30]
翻訳ガイドライン本文とは別に、用語についてまとめた文書があると良いのではないか。

https://github.com/waic/wcag20/wiki/用語・用字について をベースに、過去のissueで議論になったものなどをまとめていきたい。
 https://github.com/waic/wcag20/issues/196 も参照。

**Comment by momdo** [comment]
#18 も参照。

**Comment by DaichiImai** [comment]
↓こちらで対応中です
https://github.com/waic/translation_guidelines/pull/34

**Comment by bakera** [comment]
スプレッドシートのほうに集約することにしたので、こちらはクローズします。
