### ISSUE TITLE
引用符のルール

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/translation_guidelines#4]
原文でダブルクォーテーションを使っている文章を日本語に訳す際のルールは決めないのでしょうか？ たとえば“”にするとか、""のままにするとか、「」にするとかあるとおもいます。

**Comment by SawadaStdDesign** [comment]
（少しずれるかもしれませんが）ガイドライン上の表記でも
「以上」「以下」「超」「未満」 "3秒以上" "3秒超"
「。」「、」「，」 ":"コロン ";"セミコロン
のように使い分けられており、ルールがよく分かりません。

**Comment by momdo** [comment]
> G.4.3 引用符号
> 引用符号“　”は，語句を引用する場合，又は文字，記号，用語などを特に明らかにする必要がある場合に用いる。
> なお，かぎ括弧 「  」 は，用いない。

JIS Z8301に厳密に従う場合、かぎ括弧は使えないですね。

"（U+0022 QUOTATION MARK）をどうするのか？というのは別に議論が必要かもしれません。

**Comment by momdo** [comment]
<a href="http://jipsti.jst.go.jp/sist/qa/answer.html#q10">SIST 科学技術情報流通技術基準｜Q&A</a>にはこういう記述も見えます。

> Q10.　【引用符】　横書きの文書ではかぎ括弧（「　」）に代えてダブル・クォーテーション・マーク（二重引用符）（“　”）を使うのですか。
> 【回答】
>　SISTでは規定していませんが，JISの規格票の書き方（JIS Z 8301：規格票の様式及び作成方法）ではかぎ括弧は使わず，二重引用符（“　”）を利用するとしています。SIST 02（参照文献の書き方）では，参照文献を記述する句読点としては，日本語文献でもかぎ括弧は使わず，二重引用符に統一しています。SIST全体では不統一で，かぎ括弧と二重引用符を使い分けているわけではありませんが，両方使われています。
>　横書きでも縦書きと同じくかぎ括弧を利用する文書は多く見うけます。このように，現状はさまざまであり，作成する文書で統一を図る際にいずれかに決めればよいと考えます。このＱ＆Ａ文書では日本語にはかぎ括弧，英語には二重引用符を利用して，使い分けてみました。

**Comment by momdo** [comment]
まとめるとこういう感じでしょうか。

1. カッコの内側の内容にかかわらず、すべて“”を用いる。(JIS Z8301スタイル)
1. 内容が日本語の場合「」、内容が英語の場合“”を用いる。(SIST Q&Aスタイル)

内容によって引用符を変化させるのは、個人的にはありだと思うのですよね。たとえば、内容がなにかの`code`の場合、意図的に""で括るのはありなのではないかと。

上記を踏まえた提案：

3. 内側の内容にかかわらず、すべて“”を用いる。ただし、コードの場合は""を用いる。(JIS Z8301スタイル+)
3. 内側の内容が日本語の場合「」、内容が英語の場合“”を用いる。ただし、コードの場合は""を用いる。(SIST Q&Aスタイル+)

1~4のどれがよいか、お伺いしたく。

**Comment by momdo** [comment]
ちなみに、WAICサイト上のリソースは「」で統一されているようですが、JIS X 8341-3:2016では“”に修正されているようです。
