### ISSUE TITLE
数字の扱いに関するルールの追加

### ISSUE THREAD

**Issue by momdo** [waic/translation_guidelines#5]
https://github.com/waic/wcag20/issues/187 より

例えば、「1 つ」と「一つ」が混在しているので、統一することが望ましいという話。

## JIS Z 8301:2008 G.5 数字 (P.59)
数字は，アラビア数字を用いる。ただし，次のような場合には，漢字を用いる。
a)“ひと（つ）”“ふた（つ）”のように読む場合（例1参照）。
例1  三つ目きり  3 本一組
b)数の概念が薄い場合（例2参照）。
例2  一般用
c)概数を表す次のような場合（例3参照）。
例3  十数倍
d)大きな数を表すのに，アラビア数字を併用する場合（例4参照）。
例4  2 万回
e)慣用となっていると認められる場合（例5参照）。
例5  一酸化炭素  二等辺三角形  二乗

## JTF日本語標準スタイルガイド（翻訳用）第2.3版
http://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf#page=16

数量を表現し、数を数えられるものは算用数字を使用します。任意の数に置き換えても通用する語句がこれに該当します。序数詞（「第～回」「～番目」「～回目」）も算用数字を使います。

・算用数字を使う
1 億 2805 万人　3 つのボタン　第 3 回大会　4 か月　1 番目、2 番目　2 進法　3 次元　

慣用的表現、熟語、概数、固有名詞、副詞など、漢数字を使用することが一般的な語句では漢数字を使います。

・漢数字を使う
世界一　一時的　一部分　第三者　一種の　一部の　一番に　数百倍　二次関数　四捨五入　四角い　五大陸

ちなみにWCAG 2.0では「一つ」と記載されています。

**Comment by bakera** [comment]
ちなみにJISの規格票でも「少なくとも一つ」のような表記をしています。

**Comment by momdo** [comment]
JISもJTFも概ね同じようなことを言っていて、「ひとつ」「ふたつ」をJISにあわせて厳密に漢数字とするのが適当でしょうか。

Proposal:
数量を表現し、数を数えられるものは算用数字を使用します。任意の数に置き換えても通用する語句がこれに該当します。序数詞（～番目など）も算用数字を使います。ただし、「ひとつ」「ふたつ」と数えるものは漢数字とします。
慣用的表現、熟語、概数、固有名詞、副詞など、漢数字を使用することが一般的な語句では漢数字を使います。

- 算用数字を使う例：1 億 2805 万人　第 3 回大会　4 か月　1 番目、2 番目　2 進法　3 次元　
- 漢数字を使う例：三つのボタン　世界一　一時的　一部分　第三者　一種の　一部の　一番に　数百倍　二次関数　四捨五入　四角い　五大陸
