### ISSUE TITLE
ガイドライン（案）の注意書きについて

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/translation_guidelines#9]
「隅付き括弧（【】）は、JIS Z 8301:2011の節番号に対応」とありますが、JIS Z 8301のPDF（2008）を見る限り対応しているように見えません。
2008ではなく2011では対応しているのでしょうか？（どこで見られるでしょうか？）

**Comment by momdo** [comment]
>「隅付き括弧（【】）は、JIS Z 8301:2011の節番号に対応」とありますが、JIS Z 8301のPDF（2008）を見る限り対応しているように見えません。

対応しているようには見えない、というのは「規格書の節番号をそもそも見つけることができない」ということでしょうか。

例えばG.1であれば、JIS Z 8301:2008の52ページにあります。

**Comment by SawadaStdDesign** [comment]
ありました！
なるほど、【G◯◯】の「G」は「附属書 G」 の「G」だったんですね。
気が付きませんでした。
気が付きやすいような書きっぷりの方が良いのではないかと思います。「（附属書含む）」とか。
